name: Configurar Entorno en Push a Main

on:
  push:
    branches: [ main ]

jobs:
  setup-env:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v3


      - name: Copy .env files
        run: |
          cp ~/actions-runner/.env ~/actions-runner/_work/automatedAttendanceSystem/automatedAttendanceSystem/
          
          cp ~/actions-runner/_work/.env ~/actions-runner/_work/automatedAttendanceSystem/automatedAttendanceSystem/interface/
          
          echo "Correctly copied"

      - name: install
        run: |
          cd ~/actions-runner/_work/automatedAttendanceSystem/automatedAttendanceSystem/interface
          npm install                



      - name: Create Virtual Environment and install requirements
        run: |
            cd ~/actions-runner/_work/automatedAttendanceSystem/automatedAttendanceSystem
            
            python3 -m venv .venv
            
            #Activate VE
            source .venv/bin/activate
            
            # Install dependencies if requeriments.txt
            if [ -f "requeriments.txt" ]; then
            pip install -r requeriments.txt
            echo "Dependencies installed"
            else
            echo "File not found"
            fi
 
            deactivate


            cd ~/actions-runner/_work/automatedAttendanceSystem/automatedAttendanceSystem/interface
          
            python3 -m venv .venv
            
            source .venv/bin/activate
            
            if [ -f "../requeriments.txt" ]; then
                pip install -r ../requeriments.txt
                echo "Dependencies installes"
            else
                echo "File not found"
            fi
            
            deactivate

      - name: Protect .vite directory from being removed
        run: |
            VITE_DIR=~/actions-runner/_work/automatedAttendanceSystem/automatedAttendanceSystem/interface/.vite/deps
            
            mkdir -p $VITE_DIR
            
            touch $VITE_DIR/.runner_preserve
            
            mkdir -p ~/actions-runner/_work/automatedAttendanceSystem/automatedAttendanceSystem/.git/info
            echo "interface/.vite/" >> ~/actions-runner/_work/automatedAttendanceSystem/automatedAttendanceSystem/.git/info/exclude
            
            echo "Protected .vite directory from removal"
    
            
      - name: Restart pm2 tasks
        run: |
            sudo pm2 restart all
